version: "3.7"


services:
  cut_api:
    build: .
    env_file: .env
    ports:
      - '8008:88'
    command: uvicorn cut_api.api.main:app --host 0.0.0.0 --port 88 --reload
    networks:
      &network_mode
      - bridgenet
    volumes:
      - ./:/app
    
  redis-cut-api:
    container_name: redis-cut-api
    image: redis:6.2-alpine
    ports:
      - ${REDIS_PORT:-6378}:6378
    restart: "always"
    command: redis-server --requirepass ${REDIS_PASSWORD}  --appendonly yes --port ${REDIS_PORT}
    networks: *network_mode
    volumes:
      - "./redis/data:/data"

networks:
  bridgenet:
    driver: bridge