version: "3.7"


services:

  cut_api:
    build: .
    env_file: .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    command: uvicorn cut_api.api.main:app --host 0.0.0.0 --port ${APP_PORT} --reload
    networks:
      &network_mode
      - bridgenet
    volumes:
      - ./:/app
    depends_on:
      - redis
    
  redis:
    container_name: redis-cut-api
    image: redis:6.2-alpine
    expose: 
      - ${REDIS_PORT}
    restart: "always"
    command: redis-server --requirepass ${REDIS_PASSWORD}  --appendonly yes --port ${REDIS_PORT}
    networks: *network_mode
    volumes:
      - "./redis/data:/data"

networks:
  bridgenet:
    driver: bridge