version: "3.7"


x-common-settings: &common_settings
  networks:
    - bridgenet
  restart: "always"


services:

  cut_api:
    <<: *common_settings
    build: .
    env_file: .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    command: uvicorn cut_api.api.main:app --host 0.0.0.0 --port ${APP_PORT} --reload
    volumes:
      - ./:/app
    depends_on:
      - redis
    
  redis:
    <<: *common_settings
    image: redis:6.2-alpine
    container_name: redis-cut-api
    expose:
      - ${REDIS_PORT}
    command: redis-server --requirepass ${REDIS_PASSWORD}  --appendonly yes --port ${REDIS_PORT}
    volumes:
      - "./redis/data:/data"

networks:
  bridgenet:
    driver: bridge