version: "3.7"


services:

  cut_api:
    build: .
    env_file: .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    command: uvicorn cut_api.api.main:app --host 0.0.0.0 --port ${APP_PORT} --reload
    networks:
      &network_mode
      - bridgenet
    volumes:
      - ./:/app
    depends_on:
      - redis
    
  redis:
    container_name: redis-cut-api
    image: redis:6.2-alpine
    expose: 
      - ${REDIS_PORT}
    restart: "always"
    command: redis-server --requirepass ${REDIS_PASSWORD}  --appendonly yes --port ${REDIS_PORT}
    networks: *network_mode
    volumes:
      - "./redis/data:/data"
  
  noise-api:
    build:
      context: ./external_apis/COUP-noise-api-v2
    env_file: .env.noise
    ports:
      - '${NOISE_API_PORT}:${NOISE_API_PORT}'
    command: uvicorn noise_api.api.main:app --host 0.0.0.0 --port ${NOISE_API_PORT} --reload
    networks:
      &network_mode
      - bridgenet
    volumes:
      - ./external_apis/COUP-noise-api-v2:/app
  
  noise-api-celery-worker:
    container_name: noise-api-celery-worker
    build:
      context: ./external_apis/COUP-noise-api-v2
    env_file: .env.noise
    restart: "always"
    command: celery -A noise_api.tasks worker --loglevel=info
    networks: *network_mode
    volumes:
      - ./external_apis/COUP-noise-api-v2:/app
  
  stormwater-api:
    build:
      context: ./external_apis/COUP-stormwater-api-v2-
    env_file: .env.water
    ports:
      - '${WATER_API_PORT}:${WATER_API_PORT}'
    command: uvicorn stormwater_api.api.main:app --host 0.0.0.0 --port ${WATER_API_PORT} --reload
    networks:
      &network_mode
      - bridgenet
    volumes:
      - ./external_apis/COUP-stormwater-api-v2-:/app
  
  stormwater-api-celery-worker:
    container_name: stormwater-celery-worker
    build:
      context: ./external_apis/COUP-stormwater-api-v2-
    env_file: .env.water
    restart: "always"
    command: celery -A stormwater_api.tasks worker --loglevel=info
    networks: *network_mode
    volumes:
      - ./external_apis/COUP-stormwater-api-v2-:/app


networks:
  bridgenet:
    driver: bridge